# Generated by Django 2.2.1 on 2019-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=15)),
            ],
        ),
    ]
