# Generated by Django 2.2.1 on 2019-05-29 02:32

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=20)),
                ('doc_index', models.CharField(default='00001', max_length=15)),
                ('doc_title', models.CharField(max_length=20)),
                ('doc_writer', models.CharField(default='shyunku', max_length=20)),
                ('doc_content', models.TextField(default='')),
                ('doc_time', models.DateTimeField(auto_now_add=True)),
                ('doc_view_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SummerNote',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment')),
                ('summer_field', django_summernote.fields.SummernoteTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=25)),
                ('user_pw', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_index_recent', models.IntegerField(default=0)),
                ('comment_index_recent', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('visits_free', models.IntegerField(default=0)),
                ('visits_rout', models.IntegerField(default=0)),
                ('visits_lol', models.IntegerField(default=0)),
                ('visits_dl', models.IntegerField(default=0)),
                ('visits_web', models.IntegerField(default=0)),
                ('visits_java', models.IntegerField(default=0)),
                ('visits_window', models.IntegerField(default=0)),
                ('visits_indiv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField(default='')),
                ('comment_id', models.CharField(default='000001', max_length=15)),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented', to='home.Documents_Info')),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.User_Info')),
            ],
        ),
    ]
