# Generated by Django 2.2.1 on 2019-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=20)),
                ('doc_index', models.CharField(default='0000001', max_length=15)),
                ('doc_title', models.CharField(max_length=20)),
                ('doc_time', models.TimeField()),
                ('doc_viewe_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
                ('doc_index_recent', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Visit_Count',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_nickname',
            field=models.CharField(max_length=25),
        ),
    ]
