# Generated by Django 2.2.1 on 2019-05-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190524_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents_info',
            old_name='doc_viewe_cnt',
            new_name='doc_view_cnt',
        ),
    ]
