# Generated by Django 2.2.1 on 2019-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190524_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents_info',
            name='doc_writer',
            field=models.CharField(default='shyunku', max_length=20),
        ),
    ]
