# Generated by Django 2.2.1 on 2019-05-24 18:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
        ('home', '0005_documents_info_doc_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='SummerNote',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment')),
                ('summer_field', django_summernote.fields.SummernoteTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
        migrations.AddField(
            model_name='documents_info',
            name='doc_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='documents_info',
            name='doc_index',
            field=models.CharField(default='00001', max_length=15),
        ),
        migrations.AlterField(
            model_name='documents_info',
            name='doc_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
