# Generated by Django 2.2.1 on 2019-05-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190525_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='visits_dl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_free',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_indiv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_java',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_lol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_rout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_web',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variables',
            name='visits_window',
            field=models.IntegerField(default=0),
        ),
    ]
