# Generated by Django 2.2.1 on 2019-05-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190525_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField(default='')),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Documents_Info')),
                ('comment_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.User_Info')),
            ],
        ),
    ]
