# Generated by Django 2.2.1 on 2019-05-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented', to='home.Documents_Info'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.User_Info'),
        ),
    ]
